name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --ignore-scripts
      - run: pnpm run lint
      - run: pnpm run tsc
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --ignore-scripts
      - run: pnpm run test
